---
echo: false
---

```{r}
library(htmltools)
```


```{r}
#| file: C:/Users/AYOMIDE/Documents/R/report/FAAC/ui_function.R 
```

```{r}
page_title_nav(
  "Nigerian States and Local Governments FAAC Allocation Breakdown", 
  "2024", "2023", 
  "about"
)
```

::: {.about-page}

```{r}
div(
  class = "about-container",
  div(
    class = "faac-definition",
    
    h3(class = "con-title", "What Is The FAAC Allocation?"),
    
    p(
      class = "para",
      "
FAAC stands for Federal Account Allocation Committee. It is a committee responsible for sharing revenue generated by the federal government among the three tiers of government in Nigeria: federal, state, and local governments.
The FAAC meeting determines the amount to be shared among the three tiers of government based on the revenue generated and deductions made. 
"
    ),
    p(
      class = "para",
      "
The federal government receives the largest share, i.e., 52.68% of the total revenue, followed by states with 26.72%, and finally local governments with 20.6%. Oil-producing states receive an additional 13% of the revenue as a derivation fund based on their production quota relative to the total national oil production.
"
    ),
    p(
      class = "para",
      "
The revenue shared by FAAC is primarily derived from statutory allocations, consumption taxes such as the Value Added Tax (VAT), exchange gain differences, and the 13% derivation from the total revenue.
", 
  tags$span(
    class = "more-info", 
    tags$a(href = "https://faac.ng/about-us", "For more info visit the offical page")
  )
    ),
  ),

  div(
    class = "missing-records",
    h3(class = "con-title missing", "Caveat Regarding Missing Data"),
    p("The dataset contains the following known gaps:"),
    p(
      class = "para",
      "
      1. There is a missing record for Kwali Local Government Council (LGC) in Abuja for April 2007.
      "
    ),
    p(
      class = "para",
      "
      2. Another missing record for Brass Local Government Council (LGC) in Bayelsa state for February 2014.
      "
    ),
    p(
      class = "para",
      "
      3. There are missing records from March to November 2021 in all Local Government Councils (LGCs) nationwide. While state allocation records exist for this period, the corresponding LGC allocations were not included in the official source from the National Bureau of Statistics (NBS).
      "
    )
  ),

  div(
    class = "data-source",

    h3(class = "con-title", "Data Source:"),

    div(
      class = "img-desc",
      tags$img(src = "www/images/oag.svg", class = "img"),
      p(class = "desc", "Office of the accountant general of the federation.")
    ),
    div(
      class = "img-desc",
      tags$img(src = "www/images/nbs_logo.png", class = "img"),
      p(class = "desc", "National Bureau of Statistics.")
    ),
  ),
)
```

<br>
<br>

:::

<!------ Navigation js ------------------------------------------------------>
{{< include _page_nav_js.qmd >}}
